[server]
host = "localhost"
port = 8080

[database]
type = "postgres"
host = "db.local"
port = 5432
username = "admin"
password = "secret"

[logging]
level = "info"
output = "file"
file_path = "/var/log/server.log"

max_connections_expression_problem = "100 20 +"
